exA: point.h point.cpp shape.h shape.cpp square.h square.cpp rectangle.h rectangle.cpp circle.h circle.cpp curveCut.h curveCut.cpp graphicsWorld.h graphicsWorld.cpp
	g++ -Wall -o exA point.cpp shape.cpp square.cpp rectangle.cpp circle.cpp curveCut.cpp graphicsWorld.cpp

.PHONY: clean
clean:
	rm -f exA